services:
  content:
    build:
      context: .
      dockerfile: ./build/content.dockerfile
    depends_on:
      - content_db
    environment:
      #DATABASE_URL: FILL_ME
    restart: on-failure

  description:
    build:
      content: .
      dockerfile: ./build/feed.dockerfile
    depends_on:
      - feed_db
    environment:
      #DATABASE_URL: FILL_ME
    restart: on-failure

  profile:
    build:
      content: .
      dockerfile: ./build/profile.dockerfile
    depends_on:
      - profile_db
    environment:
      #DATABASE_URL: FILL_ME
    restart: on-failure  

  content_db:
    build:
      context: 





