version: "1.0"

services:
  gateway:
    container_name: gateway
    build:
      context: ../gateway
      dockerfile: Dockerfile
    ports:
      - "80001:8001"
    restart: always
    environment:
      - POSTGREST_HOST=host.docker.internal
      - POSTGRES_PORT=5432
    networks:
      - caught_candid
